In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import datasets
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data.csv')
df = df.replace('?',np.nan)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,heartDisease
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
  
scaler.fit(df.drop('heartDisease', axis = 1))
scaled_features = scaler.transform(df.drop('heartDisease', axis = 1))
  
df_feat = pd.DataFrame(scaled_features, columns = df.columns[:-1])
df_feat.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,0.948726,0.686202,-2.251775,0.757525,-0.264900,2.394438,1.016684,0.017197,-0.696631,1.087338,2.274579,-0.724246,0.660258
1,1.392002,0.686202,0.877985,1.611220,0.760415,-0.417635,1.016684,-1.821905,1.435481,0.397182,0.649113,2.425706,-0.882607
2,1.392002,0.686202,0.877985,-0.665300,-0.342283,-0.417635,1.016684,-0.902354,1.435481,1.346147,0.649113,1.375722,1.174546
3,-1.932564,0.686202,-0.165268,-0.096170,0.063974,-0.417635,-0.996749,1.637359,-0.696631,2.122573,2.274579,-0.724246,-0.882607
4,-1.489288,-1.457296,-1.208521,-0.096170,-0.825922,-0.417635,1.016684,0.980537,-0.696631,0.310912,-0.976352,-0.724246,-0.882607

In [6]:
x_train, x_test, y_train, y_test = train_test_split(scaled_features,df['heartDisease'],test_size=0.3)

In [7]:
classier = KNeighborsClassifier(n_neighbors=5)
classier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [8]:
y_pred=classier.predict(x_test)

In [9]:
print('confusion matrix')
print(confusion_matrix(y_test,y_pred))

confusion matrix
[[45  2  1  0  0]
 [10  4  2  1  0]
 [ 4  4  1  1  0]
 [ 2  9  2  0  2]
 [ 0  0  1  0  0]]

In [10]:
print('accuracy')
print(classification_report(y_test,y_pred))

accuracy
              precision    recall  f1-score   support

           0       0.74      0.94      0.83        48
           1       0.21      0.24      0.22        17
           2       0.14      0.10      0.12        10
           3       0.00      0.00      0.00        15
           4       0.00      0.00      0.00         1

    accuracy                           0.55        91
   macro avg       0.22      0.25      0.23        91
weighted avg       0.44      0.55      0.49        91